export default {
    products: [
        {
            _id:'45',
            name: 'Bánh mỳ',
            category: 'Food',
            image: '/images/FastFood.jpg',
            price: 20000,
            brand: 'Kitchen',
            rating: 4.5,
            numReviews: 10,
            countInStock: 8,
        },
        {
            _id:'46',
            name: 'Bún bò',
            category: 'Food',
            image: '/images/FastFood.jpg',
            price: 20000,
            brand: 'Kitchen',
            rating: 4.5,
            numReviews: 10,
            countInStock: 0,
        },
        {
            _id:'47',
            name: 'Coca',
            category: 'Drinks',
            image: '/images/FastFood.jpg',
            price: 20000,
            brand: 'Kitchen',
            rating: 4.5,
            numReviews: 10,
            countInStock: 7,
        },
        {
            _id:'48',
            name: 'Pepsi',
            category: 'Drinks',
            image: '/images/FastFood.jpg',
            price: 20000,
            brand: 'Kitchen',
            rating: 4.5,
            numReviews: 10,
            countInStock: 7,
        },
        {
            _id:'49',
            name: 'Cơm chiên',
            category: 'Food',
            image: '/images/FastFood.jpg',
            price: 20000,
            brand: 'Kitchen',
            rating: 4.5,
            numReviews: 10,
            countInStock: 10,
        },
        {
            _id:'50',
            name: 'Hủ tiếu',
            category: 'Food',
            image: '/images/FastFood.jpg',
            price: 20000,
            brand: 'Kitchen',
            rating: 4.5,
            numReviews: 10,
            countInStock: 10,
        },
    ]
}